#==========================
# include lex and yacc libraries
# enable debugging and use gnu11 standard
#==========================
LOADLIBES = -ll -ly
YFLAGS = -d
CFLAGS = -g  -std=gnu11

clean:
	rm -f ScanEx0 ScanEx1 ScanEx2 ScanEx3 *.o
	rm -rf *.dSYM
